CREATE DATABASE IF NOT EXISTS `PI_DOGTOR`;
USE `PI_DOGTOR`;

CREATE TABLE TB_MARCA (
	CODIGO_MARCA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_MARCA VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (CODIGO_MARCA)
);

CREATE TABLE TB_PROVEEDOR (
	CODIGO_PROVEEDOR INT NOT NULL AUTO_INCREMENT,
    NOMBRE_PROVEEDOR VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (CODIGO_PROVEEDOR)
);

CREATE TABLE TB_CATEGORIA (
	CODIGO_CATEGORIA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (CODIGO_CATEGORIA)
);

CREATE TABLE TB_PRODUCTO (
	CODIGO_PRODUCTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_PRODUCTO VARCHAR(255) DEFAULT NULL,
    DESCRIPCION_SIMPLE_PRODUCTO TEXT DEFAULT NULL,
    DESCRIPCION_HTML_PRODUCTO TEXT DEFAULT NULL,
    PRECIO_PRODUCTO DOUBLE DEFAULT NULL,
    STOCK_PRODUCTO INT DEFAULT NULL,
    SERIE_PRODUCTO VARCHAR(50) DEFAULT NULL,
    FOTO1_PRODUCTO LONGBLOB NOT NULL,
    FOTO2_PRODUCTO LONGBLOB NOT NULL,
    FOTO3_PRODUCTO LONGBLOB NOT NULL,
    CODIGO_MARCA INT DEFAULT NULL,
    CODIGO_CATEGORIA INT DEFAULT NULL,
    CODIGO_PROVEEDOR INT DEFAULT NULL,
    PRIMARY KEY (CODIGO_PRODUCTO),
    CONSTRAINT `TB_PRODUCTO_FK_TB_MARCA` FOREIGN KEY (CODIGO_MARCA) REFERENCES TB_MARCA (CODIGO_MARCA),
    CONSTRAINT `TB_PRODUCTO_FK_TB_CATEGORIA` FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES TB_CATEGORIA (CODIGO_CATEGORIA),
    CONSTRAINT `TB_PRODUCTO_FK_TB_PROVEEDOR` FOREIGN KEY (CODIGO_PROVEEDOR) REFERENCES TB_PROVEEDOR (CODIGO_PROVEEDOR)
);

