INSERT INTO tb_color_mascota(NOMBRE_COLOR_MASCOTA) VALUES ("Blanco y Negro");
INSERT INTO tb_color_mascota(NOMBRE_COLOR_MASCOTA) VALUES ("Blanco y Gris");
INSERT INTO tb_color_mascota(NOMBRE_COLOR_MASCOTA) VALUES ("Blanco y Crema");
INSERT INTO tb_color_mascota(NOMBRE_COLOR_MASCOTA) VALUES ("Blanco");
INSERT INTO tb_color_mascota(NOMBRE_COLOR_MASCOTA) VALUES ("Negro");
INSERT INTO tb_color_mascota(NOMBRE_COLOR_MASCOTA) VALUES ("Crema");
INSERT INTO tb_color_mascota(NOMBRE_COLOR_MASCOTA) VALUES ("Crema, Blanco, y Negro");

INSERT INTO tb_especie_mascota(NOMBRE_ESPECIE_MASCOTA) VALUES ("Perro");
INSERT INTO tb_especie_mascota(NOMBRE_ESPECIE_MASCOTA) VALUES ("Gato");
INSERT INTO tb_especie_mascota(NOMBRE_ESPECIE_MASCOTA) VALUES ("Conejo");
INSERT INTO tb_especie_mascota(NOMBRE_ESPECIE_MASCOTA) VALUES ("Hámster");

INSERT INTO tb_sexo_mascota(NOMBRE_SEXO_MASCOTA) VALUES ("Hembra");
INSERT INTO tb_sexo_mascota(NOMBRE_SEXO_MASCOTA) VALUES ("Macho");
INSERT INTO tb_sexo_mascota(NOMBRE_SEXO_MASCOTA) VALUES ("Indeterminado");

INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Chihuahua", 1);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Pastor Alemán", 1);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Husky Siberiano", 1);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Persa", 2);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Siamés", 2);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Sphynx", 2);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Californiano", 3);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Holandés", 3);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Arlequín", 3);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Ruso", 4);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Sirio", 4);
INSERT INTO tb_raza_mascota(NOMBRE_RAZA_MASCOTA, CODIGO_ESPECIE_MASCOTA) VALUES ("Chino", 4);