USE pi_dogtor;

DROP PROCEDURE IF EXISTS TEST;

DELIMITER //

CREATE PROCEDURE TEST(
    IN TIPO INTEGER, ESPECIALIDAD INTEGER, ESPECIALISTA INTEGER, DIA INTEGER
)
BEGIN
    IF TIPO LIKE 0 AND ESPECIALIDAD LIKE 0 AND ESPECIALISTA LIKE 0 AND DIA LIKE 0 THEN
        SELECT * FROM tb_servicio serv CROSS JOIN tb_tipo_servicio tts on tts.CODIGO_TIPO_SERVICIO = serv.CODIGO_TIPO_SERVICIO CROSS JOIN tb_especialidad te on te.CODIGO_ESPECIALIDAD = serv.CODIGO_ESPECIALIDAD CROSS JOIN tb_usuario tu on tu.CODIGO_USUARIO = serv.CODIGO_ESPECIALISTA CROSS JOIN tb_dia_semana tds on tds.CODIGO_DIA_SEMANA = serv.CODIGO_DIA_SEMANA;
    ELSE
        IF TIPO NOT LIKE 0 AND ESPECIALIDAD NOT LIKE 0 AND ESPECIALISTA NOT LIKE 0 AND DIA NOT LIKE 0 THEN
            SELECT * FROM tb_servicio serv CROSS JOIN tb_tipo_servicio tts on tts.CODIGO_TIPO_SERVICIO = serv.CODIGO_TIPO_SERVICIO CROSS JOIN tb_especialidad te on te.CODIGO_ESPECIALIDAD = serv.CODIGO_ESPECIALIDAD CROSS JOIN tb_usuario tu on tu.CODIGO_USUARIO = serv.CODIGO_ESPECIALISTA CROSS JOIN tb_dia_semana tds on tds.CODIGO_DIA_SEMANA = serv.CODIGO_DIA_SEMANA
            WHERE serv.CODIGO_TIPO_SERVICIO LIKE TIPO AND serv.CODIGO_ESPECIALIDAD LIKE ESPECIALIDAD AND serv.CODIGO_ESPECIALISTA LIKE ESPECIALISTA AND serv.CODIGO_DIA_SEMANA LIKE DIA;
        ELSE
            IF TIPO NOT LIKE 0 AND ESPECIALIDAD LIKE 0 AND ESPECIALISTA LIKE 0 AND DIA LIKE 0 THEN
                SELECT * FROM tb_servicio serv CROSS JOIN tb_tipo_servicio tts on tts.CODIGO_TIPO_SERVICIO = serv.CODIGO_TIPO_SERVICIO CROSS JOIN tb_especialidad te on te.CODIGO_ESPECIALIDAD = serv.CODIGO_ESPECIALIDAD CROSS JOIN tb_usuario tu on tu.CODIGO_USUARIO = serv.CODIGO_ESPECIALISTA CROSS JOIN tb_dia_semana tds on tds.CODIGO_DIA_SEMANA = serv.CODIGO_DIA_SEMANA
                WHERE serv.CODIGO_TIPO_SERVICIO LIKE TIPO;
            END IF;

            IF TIPO NOT LIKE 0 AND ESPECIALIDAD NOT LIKE 0 AND ESPECIALISTA LIKE 0 AND DIA LIKE 0 THEN
                SELECT * FROM tb_servicio serv CROSS JOIN tb_tipo_servicio tts on tts.CODIGO_TIPO_SERVICIO = serv.CODIGO_TIPO_SERVICIO CROSS JOIN tb_especialidad te on te.CODIGO_ESPECIALIDAD = serv.CODIGO_ESPECIALIDAD CROSS JOIN tb_usuario tu on tu.CODIGO_USUARIO = serv.CODIGO_ESPECIALISTA CROSS JOIN tb_dia_semana tds on tds.CODIGO_DIA_SEMANA = serv.CODIGO_DIA_SEMANA
                WHERE serv.CODIGO_TIPO_SERVICIO LIKE TIPO AND serv.CODIGO_ESPECIALIDAD LIKE ESPECIALIDAD;
            END IF;

            IF TIPO NOT LIKE 0 AND ESPECIALIDAD NOT LIKE 0 AND ESPECIALISTA NOT LIKE 0 AND DIA LIKE 0 THEN
                SELECT * FROM tb_servicio serv CROSS JOIN tb_tipo_servicio tts on tts.CODIGO_TIPO_SERVICIO = serv.CODIGO_TIPO_SERVICIO CROSS JOIN tb_especialidad te on te.CODIGO_ESPECIALIDAD = serv.CODIGO_ESPECIALIDAD CROSS JOIN tb_usuario tu on tu.CODIGO_USUARIO = serv.CODIGO_ESPECIALISTA CROSS JOIN tb_dia_semana tds on tds.CODIGO_DIA_SEMANA = serv.CODIGO_DIA_SEMANA
                WHERE serv.CODIGO_TIPO_SERVICIO LIKE TIPO AND serv.CODIGO_ESPECIALIDAD LIKE ESPECIALIDAD AND serv.CODIGO_ESPECIALISTA LIKE ESPECIALISTA;
            END IF;
        END IF;
    END IF;
END //

DELIMITER ;

CALL TEST(1, 5, 0, 0);